from tkinter import*
from tkinter.ttk import*
root=Tk()
root.geometry('600x600')
v=StringVar()
v.set('None')
fruit=Label(root,text=    'Your Favourite Fruit:     ')
vegetable=Label(root,text='Your Favourite Vegetable: ')
f=StringVar()
f.set('None')
vegetabless=['None','Carrot','Onion','Tomato']
vfm=OptionMenu(root,f,*vegetabless)
fruit.place(x=250,y=250)
vegetable.place(x=250,y=290)
om=OptionMenu(root,v,'None','Orange','Apple','Banana')
om.place(x=389,y=250)
vfm.place(x=389,y=290)
def submitted():
    results_f=Label(root,text='Your Favourite Fruit is: {} '.format(v.get()))
    result_v=Label(root,text='Your Favourite Vegetable is: {}'.format(f.get()))
    result_v.place(x=250,y=400)
    results_f.place(x=250,y=430)
submit=Button(root,command=submitted,text='Submit')
submit.place(x=300,y=350)
root.mainloop()