import tempfile
import os
import pathlib


def generate_file():
    checking = tempfile.mkstemp(
        ".py",  # suffix by default will be generated by some internals
        "testing",  # prefix by default will be generated by internals
        pathlib.Path(__file__).parent,  # directory (by default it uses the temp folder in the system)
        True  # open in text or binary (true for text mode) default false
    )
    print(checking)  # returns tuple of os handler(integer) and the path

    # we have to manually open the file
    temp = pathlib.Path(checking[1])
    temp.write_text("print('Hello World')")
    print(temp.read_text())
    return checking[0], str(temp)


# we have manually delete the file
note = generate_file()
os.close(note[0])
os.remove(note[1])
