# -*- coding: utf-8 -*-
"""19-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gQXePJfzgJsIPxUKxMryENJcXV4eSW3R
"""

import pandas

#creating the exam dataframe with name,score,attempts and qualify as it's columns

cols=['name','score','attempts','qualify']
df={}
df=eval(input('Enter the Data Frame: '))
exam=pandas.DataFrame(df)
print(exam)

# print the max score secured by either students in 'yes' or 'no' in qualification
score=exam.groupby('qualify')
print(score.max())
print()
print(score.get_group('yes').max())

#3)perform loc and iloc operations on given dataframe a=DataFrame([3,6,16,32,18,36,19,38,8,16,5,10]) loc[8],df.iloc[:2] loc[:5],iloc[45]
a=pandas.DataFrame([3,6,16,32,18,36,19,38,8,16,5,10])
print(a.loc[8])
print()
print()
print()
print(a.iloc[:2])
print()
print()
print()
print(a.loc[:5])
print()
print()
print()
print(a.iloc[45])