# -*- coding: utf-8 -*-
"""20-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hXDPdM4iGsssl4mg_QY6ubzsKqGZj2zF
"""

import pandas

df=pandas.read_csv('ballons.csv')
df

# first n elements by default n=5 
df.head()

# last n elements by default n=5 
df.tail()

# rows with indexes 2,3,4
df[2:5]

# columns in the ballons.csv
print(df.columns)

# max row in the table in terms of the size colums
print(df['size'].max())

# drop the column inflated
new_df=df.drop('inflated',axis=1)
new_df

# print first 5 rows and last 5 columns of new_df
print(new_df.head())

print(new_df.tail())

# using iloc print first 3 columns
print(df.iloc[:,:3])

print(new_df.iloc[:,:3])

# convert new_df into new csv without the index
fname='purified_ballons.csv'
new_df.to_csv(fname,index=False)

fg=pandas.read_csv(fname)
fg